app.name=${APP_NAME:${HOSTNAME:unknown}}

quarkus.http.port=${HTTP_PORT:8080}
quarkus.http.ssl-port=${HTTP_PORT:8443}

quarkus.tls.key-store.pem.0.cert=${TLS_CERT_PATH:}
quarkus.tls.key-store.pem.0.key=${TLS_KEY_PATH:}

enabled.liveness=${LIVENESS:true}
enabled.readiness=${READINESS:true}

quarkus.rest-client.service-client-api.url=${SERVICE_CLIENT_URL:localhost:8080}


