quarkus.http.ssl-port=${APP_PORT:8080}
app.name=${APP_NAME:HOSTNAME}
enabled.liveness=${LIVENESSS:true}
enabled.readiness=${READINESS:true}

quarkus.rest-client.serviceb-api.url=${SERVICE_CLIENT_URL:localhost:8080}

app.name=${APP_NAME:HOSTNAME}